# Generated by Django 5.1.6 on 2025-05-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_tag_alter_article_options_scope_article_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scope",
            options={"ordering": ["-is_main", "tag__name"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Раздел",
                "verbose_name_plural": "Разделы",
            },
        ),
        migrations.AlterField(
            model_name="scope",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="Основной раздел"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название раздела"),
        ),
    ]
