# Generated by Django 4.2.20 on 2025-04-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="phone",
            name="price",
            field=models.IntegerField(),
        ),
    ]
