# Generated by Django 5.0 on 2025-10-10 16:19

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Контакт", "verbose_name_plural": "Контакты"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-dt"],
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Элемент заказа",
                "verbose_name_plural": "Элементы заказа",
            },
        ),
        migrations.AlterModelOptions(
            name="parameter",
            options={"verbose_name": "Параметр", "verbose_name_plural": "Параметры"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterModelOptions(
            name="productinfo",
            options={
                "verbose_name": "Информация о продукте",
                "verbose_name_plural": "Информация о продуктах",
            },
        ),
        migrations.AlterModelOptions(
            name="productparameter",
            options={
                "verbose_name": "Параметр продукта",
                "verbose_name_plural": "Параметры продуктов",
            },
        ),
        migrations.AlterModelOptions(
            name="shop",
            options={"verbose_name": "Магазин", "verbose_name_plural": "Магазины"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["email"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", backend.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
