# Generated by Django 5.2.8 on 2025-11-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
