version: '3.8'

services:
  web:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000